//! The driver: one object that turns socket bytes into answers.
//!
//! Everything below this is a layer that does one thing. This sequences them, holds the
//! state between them, and gives the application a single object to feed.
//!
//! ```text
//!   bytes from the socket ──▶ Client::feed ──▶ [Step]
//!   Client::call(request)  ──▶ msg_id
//!   Client::on_modpow(r)   ──▶ [Step]
//! ```
//!
//! # Still no I/O
//!
//! [`Step::Send`] hands back framed bytes for the caller to write; nothing here touches a
//! socket, a clock or a random source. The clock comes in as an argument because MTProto
//! stamps every message with one and this crate must stay testable without one; the
//! randomness comes in as an [`Rng`].
//!
//! # Why the modular exponentiations leave the building
//!
//! Twice per login, [`Step::ModPow`] asks the caller to compute `base^exp mod m`. It takes
//! 815 ms on an E72, and 815 ms inside `rust_step` freezes the window server — the whole
//! phone, not just this application, with no watchdog to recover. The caller puts it on the
//! worker thread, which is proven on that hardware: 1933 ms of wall time with 27 GUI ticks
//! served through it.
//!
//! The asymmetry is deliberate. AES and SHA-256 run inline because they are microseconds;
//! only the exponentiation is worth the round trip through another thread.

use alloc::collections::BTreeMap;
use alloc::vec::Vec;

use crate::crypto::Rng;
use crate::handshake::{self, AuthKey, Handshake};
use crate::rpc::{self, Update};
use crate::session::{self, Session};
use crate::transport::{self, Frame, Transport};

#[derive(Clone, PartialEq, Eq, Debug)]
pub enum Error {
    Handshake(handshake::Error),
    Session(session::Error),
    Rpc(rpc::Error),
    Transport(transport::Error),
    /// The server sent a transport-level error, outside any encryption. `-404` means it has
    /// forgotten our auth key and the handshake must be redone from scratch.
    Server(i32),
    /// A call was made before the handshake finished.
    NotReady,
}

pub type Result<T> = core::result::Result<T, Error>;

/// What the caller should do, or what happened.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum Step {
    /// Write these bytes to the socket. Already framed.
    Send(Vec<u8>),
    /// Compute `base^exp mod modulus` off this thread and return it through
    /// [`Client::on_modpow`]. See the module docs on why.
    ModPow { base: Vec<u8>, exp: Vec<u8>, modulus: Vec<u8> },
    /// The handshake finished. Persist the key: redoing it costs two exponentiations and
    /// four round trips, which on this hardware is most of a login.
    Ready,
    /// Something arrived.
    Update(Update),
}

enum Phase {
    Handshaking(Handshake),
    Ready(Session),
}

/// One connection to one data centre.
pub struct Client {
    transport: Transport,
    phase: Phase,
    auth: Option<AuthKey>,
    session_id: u64,
    /// Server time minus local time, applied to every `msg_id`.
    ///
    /// `None` until the first message with a local time goes out, because the handshake
    /// reports the server's clock and nothing below this layer has one to compare it to.
    /// An earlier version stored the server's absolute time in a field named `time_offset`
    /// and produced `msg_id`s 56 years ahead; the server answered `bad_msg_notification`
    /// code 16. No offline test could have caught it — both sides of every fixture shared
    /// the same wrong clock — and the live run found it in one line.
    time_offset: Option<i32>,
    /// What the server said its clock read, kept so the offset can be computed once a local
    /// time is available.
    server_time: i32,
    /// Messages received and not yet acknowledged. Flushed by [`Client::pending_ack`].
    to_ack: Vec<u64>,
    /// Requests sent and not yet answered, so a reply can be attributed. The value is
    /// whatever tag the caller passed to [`Client::call`].
    inflight: BTreeMap<u64, u32>,
}

impl Client {
    /// Begin a handshake. The returned step is the first message to send.
    pub fn connect<R: Rng>(rng: &mut R) -> (Self, Step) {
        let (hs, action) = Handshake::start(rng);
        let c = Client {
            transport: Transport::new(),
            phase: Phase::Handshaking(hs),
            auth: None,
            session_id: rng_u64(rng),
            time_offset: None,
            server_time: 0,
            to_ack: Vec::new(),
            inflight: BTreeMap::new(),
        };
        let step = c.action_to_step(action);
        (c, step)
    }

    /// Resume with a stored key, skipping the handshake entirely.
    ///
    /// The session id must be **new**: the server uses it to tell a reconnect from a
    /// duplicate, and reusing one across connections makes a resumed session look like a
    /// replay. Nothing enforces that here because nothing here can — it is generated by the
    /// caller from the same `Rng` the handshake uses.
    /// `time_offset` is the value persisted alongside the key. Pass `0` if none was stored:
    /// a wrong offset is only usable if the handset's clock is within 30 seconds of the
    /// server's, and the server will say so with `bad_msg_notification` code 16 rather than
    /// failing silently.
    pub fn resume<R: Rng>(auth: AuthKey, time_offset: i32, rng: &mut R) -> Self {
        let session_id = rng_u64(rng);
        let server_time = auth.server_time;
        Client {
            transport: Transport::new(),
            phase: Phase::Ready(Session::new(&auth, session_id)),
            auth: Some(auth),
            session_id,
            time_offset: Some(time_offset),
            server_time,
            to_ack: Vec::new(),
            inflight: BTreeMap::new(),
        }
    }

    /// The four bytes that must precede everything on a new connection.
    pub fn greeting(&self) -> &'static [u8] {
        self.transport.greeting()
    }

    /// The negotiated key, once there is one.
    pub fn auth_key(&self) -> Option<&AuthKey> {
        self.auth.as_ref()
    }

    pub fn is_ready(&self) -> bool {
        matches!(self.phase, Phase::Ready(_))
    }

    /// Server time minus local time, in seconds, once it is known.
    ///
    /// Persist this next to the key. Without it a resumed session starts with whatever the
    /// handset's clock says, and a phone whose clock is a minute out cannot send anything.
    pub fn time_offset(&self) -> Option<i32> {
        self.time_offset
    }

    /// The offset, computing it from `unix_time` on first use.
    fn offset(&mut self, unix_time: i64) -> i64 {
        match self.time_offset {
            Some(o) => o as i64,
            None => {
                let o = self.server_time as i64 - unix_time;
                self.time_offset = Some(o as i32);
                o
            }
        }
    }

    /// Send a request. Returns the `msg_id`, which the matching [`Update::Result`] carries.
    ///
    /// `tag` is the caller's own label, handed back by [`Client::tag_of`] — a small integer
    /// rather than a closure, because a closure would mean an allocation per call and a
    /// lifetime this crate cannot express without `std`.
    pub fn call<R: Rng>(
        &mut self,
        body: &[u8],
        tag: u32,
        unix_time: i64,
        nanos: u32,
        rng: &mut R,
    ) -> Result<(u64, Step)> {
        if !self.is_ready() {
            return Err(Error::NotReady);
        }
        let offset = self.offset(unix_time);
        let Phase::Ready(session) = &mut self.phase else {
            return Err(Error::NotReady);
        };
        let corrected = unix_time + offset;
        let msg_id = session.next_msg_id(corrected, nanos);
        let seq = session.next_seq(true);
        let wire = session.encrypt(msg_id, seq, body, rng).map_err(Error::Session)?;
        self.inflight.insert(msg_id, tag);
        Ok((msg_id, Step::Send(Transport::frame(&wire))))
    }

    /// The tag given to the call that produced `req_msg_id`, consuming it.
    pub fn tag_of(&mut self, req_msg_id: u64) -> Option<u32> {
        self.inflight.remove(&req_msg_id)
    }

    /// Acknowledge everything received since the last call, if anything.
    ///
    /// Not sent automatically inside [`Client::feed`], because an ack is itself a message
    /// and building one mid-parse would mean producing sends in the middle of consuming
    /// receives. The caller drains this after handling a batch — and must, or the server
    /// resends every unacknowledged message on a timer, forever.
    pub fn pending_ack<R: Rng>(
        &mut self,
        unix_time: i64,
        nanos: u32,
        rng: &mut R,
    ) -> Option<Step> {
        if self.to_ack.is_empty() {
            return None;
        }
        if !self.is_ready() {
            return None;
        }
        let offset = self.offset(unix_time);
        let Phase::Ready(session) = &mut self.phase else {
            return None;
        };
        let body = rpc::msgs_ack(&self.to_ack);
        self.to_ack.clear();
        let msg_id = session.next_msg_id(unix_time + offset, nanos);
        // false: an ack is not content and must not advance the sequence. Counting it
        // drifts the client out of step with the server and messages start being ignored.
        let seq = session.next_seq(false);
        let wire = session.encrypt(msg_id, seq, &body, rng).ok()?;
        Some(Step::Send(Transport::frame(&wire)))
    }

    /// Feed bytes from the socket. Returns everything that became knowable.
    ///
    /// Call with whatever arrived, however little. One TCP read is not one message: it can
    /// be a fragment, or three messages at once, and both are handled here rather than by
    /// the caller.
    pub fn feed<R: Rng>(&mut self, bytes: &[u8], rng: &mut R) -> Result<Vec<Step>> {
        self.transport.feed(bytes);
        let mut steps = Vec::new();

        loop {
            match self.transport.next().map_err(Error::Transport)? {
                Frame::Incomplete => break,
                Frame::Error(code) => return Err(Error::Server(code)),
                Frame::Message(payload) => {
                    self.on_frame(&payload, &mut steps, rng)?;
                }
            }
        }
        Ok(steps)
    }

    /// Return the result of a [`Step::ModPow`].
    pub fn on_modpow<R: Rng>(&mut self, result: &[u8], rng: &mut R) -> Result<Vec<Step>> {
        let Phase::Handshaking(hs) = &mut self.phase else {
            return Err(Error::NotReady);
        };
        let action = hs.on_modpow(result, rng).map_err(Error::Handshake)?;
        Ok(self.take_action(action))
    }

    fn on_frame<R: Rng>(&mut self, payload: &[u8], steps: &mut Vec<Step>, rng: &mut R)
        -> Result<()>
    {
        match &mut self.phase {
            Phase::Handshaking(hs) => {
                let action = hs.on_message(payload, rng).map_err(Error::Handshake)?;
                steps.extend(self.take_action(action));
            }
            Phase::Ready(session) => {
                let msg = session.decrypt(payload).map_err(Error::Session)?;
                let updates = rpc::unwrap(msg.msg_id, &msg.body).map_err(Error::Rpc)?;
                for u in updates {
                    if let Some(id) = u.needs_ack() {
                        self.to_ack.push(id);
                    }
                    // The salt rotates on its own schedule and the server rejects messages
                    // using the old one. Adopting it here rather than making the caller do
                    // it removes a failure that appears an hour after login and looks like
                    // the network.
                    match &u {
                        Update::NewSalt { salt } | Update::NewSession { salt, .. } => {
                            session.set_salt(*salt);
                        }
                        _ => {}
                    }
                    steps.push(Step::Update(u));
                }
            }
        }
        Ok(())
    }

    /// Convert a handshake action, and transition when it finishes.
    fn take_action(&mut self, action: handshake::Action) -> Vec<Step> {
        match action {
            handshake::Action::Done(auth) => {
                self.server_time = auth.server_time;
                self.phase = Phase::Ready(Session::new(&auth, self.session_id));
                self.auth = Some(*auth);
                alloc::vec![Step::Ready]
            }
            other => alloc::vec![self.action_to_step(other)],
        }
    }

    fn action_to_step(&self, action: handshake::Action) -> Step {
        match action {
            // Handshake messages are unencrypted and carry their own header, which needs a
            // msg_id. Zero works: the server does not check it before a key exists, and
            // taking a clock here would put one into a crate that has managed without.
            handshake::Action::Send(body) => {
                Step::Send(Transport::frame(&handshake::unencrypted(0, &body)))
            }
            handshake::Action::ModPow { base, exp, modulus } => {
                Step::ModPow { base, exp, modulus }
            }
            handshake::Action::Done(_) => unreachable!("handled in take_action"),
        }
    }
}

fn rng_u64<R: Rng>(rng: &mut R) -> u64 {
    let mut b = [0u8; 8];
    rng.fill(&mut b);
    u64::from_le_bytes(b)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::testing::CountingRng;
    use crate::tl::Writer;

    fn key() -> AuthKey {
        let mut k = [0u8; 256];
        for (i, b) in k.iter_mut().enumerate() {
            *b = (i as u8).wrapping_mul(11).wrapping_add(5);
        }
        AuthKey { key: k, id: 0x0102_0304_0506_0708, salt: [9; 8], server_time: 0 }
    }

    #[test]
    fn a_fresh_client_sends_req_pq_first() {
        let mut rng = CountingRng(0);
        let (_c, step) = Client::connect(&mut rng);
        let Step::Send(bytes) = step else { panic!("expected a send") };
        // 4 length + 20 header + 4 ctor + 16 nonce.
        assert_eq!(bytes.len(), 44);
        assert_eq!(&bytes[24..28], &0xbe7e_8ef1u32.to_le_bytes());
    }

    #[test]
    fn a_resumed_client_skips_straight_to_ready() {
        let mut rng = CountingRng(0);
        let c = Client::resume(key(), 17, &mut rng);
        assert!(c.is_ready());
        assert_eq!(c.time_offset(), Some(17));
    }

    #[test]
    fn a_call_before_the_handshake_is_refused() {
        let mut rng = CountingRng(0);
        let (mut c, _) = Client::connect(&mut rng);
        assert_eq!(c.call(b"x", 1, 0, 0, &mut rng), Err(Error::NotReady));
    }

    #[test]
    fn a_reply_is_attributed_to_its_call() {
        let mut rng = CountingRng(0);
        let mut c = Client::resume(key(), 17, &mut rng);
        let (msg_id, _) = c.call(&rpc::get_config(), 42, 1_700_000_000, 0, &mut rng).unwrap();
        assert_eq!(c.tag_of(msg_id), Some(42));
        // Consumed: a second reply to the same call is a duplicate, and returning the tag
        // again would deliver the answer twice.
        assert_eq!(c.tag_of(msg_id), None);
    }

    #[test]
    fn the_time_offset_is_applied_to_outgoing_messages() {
        // A handset's clock is set by hand and the server rejects anything more than 30 s
        // out. Without the offset a phone a minute slow cannot send at all, and the error
        // it gets back does not mention the clock.
        let mut rng = CountingRng(0);
        let mut c = Client::resume(key(), 17, &mut rng);
        let (with_offset, _) = c.call(b"a", 1, 1_700_000_000, 0, &mut rng).unwrap();
        assert_eq!(with_offset >> 32, 1_700_000_017, "the offset was not applied");
    }

    #[test]
    fn incoming_messages_accumulate_acks() {
        let mut rng = CountingRng(0);
        let mut c = Client::resume(key(), 17, &mut rng);
        // Build a server message carrying an unknown constructor, which needs acking.
        let s = Session::new(&key(), c.session_id);
        let mut w = Writer::new();
        w.ctor(0x1234_5678);
        let wire = s.encrypt_as_server(0x600d_0000_0000_0000, 2, &w.finish(), &mut rng).unwrap();

        assert!(c.pending_ack(0, 0, &mut rng).is_none(), "nothing to ack yet");
        let steps = c.feed(&Transport::frame(&wire), &mut rng).unwrap();
        assert!(matches!(steps[0], Step::Update(Update::Unknown { .. })));
        assert!(c.pending_ack(0, 0, &mut rng).is_some(), "the message was not queued for ack");
        assert!(c.pending_ack(0, 0, &mut rng).is_none(), "the queue was not drained");
    }

    #[test]
    fn a_new_salt_is_adopted_without_the_caller_asking() {
        // Ignoring bad_server_salt produces a client that works for an hour and then has
        // every message rejected, which looks like the network rather than like a salt.
        let mut rng = CountingRng(0);
        let mut c = Client::resume(key(), 17, &mut rng);
        let s = Session::new(&key(), c.session_id);

        let mut w = Writer::new();
        w.ctor(rpc::BAD_SERVER_SALT).ulong(1).uint(0).int(48).ulong(0xfeed_face_cafe_beef);
        let wire = s.encrypt_as_server(16, 2, &w.finish(), &mut rng).unwrap();
        c.feed(&Transport::frame(&wire), &mut rng).unwrap();

        // The next outgoing message must carry the new salt. Checked by decrypting it,
        // since the salt lives inside the encryption.
        let (_, step) = c.call(b"x", 1, 1_700_000_000, 0, &mut rng).unwrap();
        let Step::Send(bytes) = step else { panic!() };
        let seen = s.decrypt_as_client(&bytes[4..]).unwrap();
        assert_eq!(seen.salt, 0xfeed_face_cafe_beef);
    }

    #[test]
    fn a_transport_error_stops_rather_than_being_parsed() {
        let mut rng = CountingRng(0);
        let mut c = Client::resume(key(), 17, &mut rng);
        let mut frame = 4u32.to_le_bytes().to_vec();
        frame.extend_from_slice(&(-404i32).to_le_bytes());
        assert_eq!(c.feed(&frame, &mut rng), Err(Error::Server(-404)));
    }

    #[test]
    fn a_message_split_across_reads_is_reassembled() {
        let mut rng = CountingRng(0);
        let mut c = Client::resume(key(), 17, &mut rng);
        let s = Session::new(&key(), c.session_id);
        let mut w = Writer::new();
        w.ctor(rpc::PONG).ulong(1).ulong(0xabc);
        let wire = Transport::frame(&s.encrypt_as_server(16, 2, &w.finish(), &mut rng).unwrap());

        for b in &wire[..wire.len() - 1] {
            assert!(c.feed(&[*b], &mut rng).unwrap().is_empty(), "completed early");
        }
        let steps = c.feed(&wire[wire.len() - 1..], &mut rng).unwrap();
        assert_eq!(steps, alloc::vec![Step::Update(Update::Pong { ping_id: 0xabc })]);
    }
}
